[tool.towncrier]
    template = ".towncrier-template.rst"
    underlines = ["-"]
    title_format = "{version} ({project_date})"
    issue_format = "`#{issue} <https://github.com/acsone/click-odoo/issues/{issue}>`_"
    directory = "newsfragments/"
    filename = "CHANGES.rst"
